# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 hidpi=on'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 160

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#
# Mouse follows focus when focused window changes
on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -160'
    alt-equal = 'resize smart +160'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
    alt-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
    alt-shift-3 = 'move-node-to-workspace --focus-follows-window 3'
    alt-shift-4 = 'move-node-to-workspace --focus-follows-window 4'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-semicolon = 'join-with left'
    alt-quote = 'join-with right'
    alt-f = 'layout floating tiling' # Toggle between floating and tiling layout
    alt-r = 'flatten-workspace-tree' # reset layout
    alt-z = 'macos-native-fullscreen'
    alt-backslash = 'layout tiles accordion'
    alt-backspace = 'close-all-windows-but-current'
    alt-esc = 'reload-config'

    # App shortcuts
    alt-enter = 'exec-and-forget open -n -a Ghostty.app'
    alt-a = 'exec-and-forget open -a ChatGPT.app'
    alt-b = '''exec-and-forget osascript -e '
    tell application "Google Chrome"
        make new window
        activate
    end tell'
    '''
    alt-c = 'exec-and-forget open -a Google\ Chat.app'
    alt-d = 'exec-and-forget open -a Google\ Calendar.app'
    alt-e = 'exec-and-forget open -a Finder.app'
    alt-i = 'exec-and-forget open -a Gmail.app'
    alt-m = 'exec-and-forget open "https://bleech.monday.com/my_inbox"'
    alt-n = 'exec-and-forget open -a Notes.app'
    alt-p = 'exec-and-forget open "https://drive.google.com/drive/folders/1A5sRwrf1xUYMAasHINA11GCLESSSe5RQ"'
    alt-s = 'exec-and-forget open "https://bleech.monday.com/boards/945652202/views/160554991"'
    alt-v = 'exec-and-forget open -a Google\ Meet.app'
    alt-w = 'exec-and-forget open -a iA\ Writer.app'

[[on-window-detected]]
  if.app-name-regex-substring = 'Finder'
  run = 'layout floating'

[[on-window-detected]]
  if.app-name-regex-substring = 'Messages'
  run = 'layout floating'

[[on-window-detected]]
  if.app-name-regex-substring = 'Harvest'
  run = 'layout floating'

[[on-window-detected]]
  if.app-name-regex-substring = '1Password'
  run = 'layout floating'

[[on-window-detected]]
  if.app-name-regex-substring = 'Gmail'
  run = 'move-node-to-workspace 2'

[[on-window-detected]]
  if.app-name-regex-substring = 'Google Chat'
  run = 'move-node-to-workspace 2'

[[on-window-detected]]
  if.app-name-regex-substring = 'Calendar'
  run = 'move-node-to-workspace 3'

[[on-window-detected]]
  if.app-name-regex-substring = 'Notes'
  run = 'move-node-to-workspace 3'

[[on-window-detected]]
  if.app-name-regex-substring = 'Google Meet'
  run = 'move-node-to-workspace 4'

[[on-window-detected]]
  if.app-name-regex-substring = 'Microsoft Teams'
  run = 'move-node-to-workspace 4'

[[on-window-detected]]
  if.app-name-regex-substring = 'zoom.us'
  run = 'move-node-to-workspace 4'

