# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 hidpi=on'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 160

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-ctrl-cmd-h = 'focus left'
    alt-ctrl-cmd-j = 'focus down'
    alt-ctrl-cmd-k = 'focus up'
    alt-ctrl-cmd-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-ctrl-cmd-shift-h = 'move left'
    alt-ctrl-cmd-shift-j = 'move down'
    alt-ctrl-cmd-shift-k = 'move up'
    alt-ctrl-cmd-shift-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-ctrl-cmd-minus = 'resize smart -160'
    alt-ctrl-cmd-equal = 'resize smart +160'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-ctrl-cmd-1 = 'workspace 1'
    alt-ctrl-cmd-2 = 'workspace 2'
    alt-ctrl-cmd-3 = 'workspace 3'
    alt-ctrl-cmd-4 = 'workspace 4'
    alt-ctrl-cmd-5 = 'workspace 5'
    alt-ctrl-cmd-6 = 'workspace 6'
    alt-ctrl-cmd-7 = 'workspace 7'
    alt-ctrl-cmd-8 = 'workspace 8'
    alt-ctrl-cmd-9 = 'workspace 9'
    alt-ctrl-cmd-0 = 'workspace 10'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-ctrl-cmd-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
    alt-ctrl-cmd-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
    alt-ctrl-cmd-shift-3 = 'move-node-to-workspace --focus-follows-window 3'
    alt-ctrl-cmd-shift-4 = 'move-node-to-workspace --focus-follows-window 4'
    alt-ctrl-cmd-shift-5 = 'move-node-to-workspace --focus-follows-window 5'
    alt-ctrl-cmd-shift-6 = 'move-node-to-workspace --focus-follows-window 6'
    alt-ctrl-cmd-shift-7 = 'move-node-to-workspace --focus-follows-window 7'
    alt-ctrl-cmd-shift-8 = 'move-node-to-workspace --focus-follows-window 8'
    alt-ctrl-cmd-shift-9 = 'move-node-to-workspace --focus-follows-window 9'
    alt-ctrl-cmd-shift-0 = 'move-node-to-workspace --focus-follows-window 10'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-ctrl-cmd-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-ctrl-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-shift-f = 'layout floating tiling'
    alt-ctrl-cmd-r = 'flatten-workspace-tree'
    alt-ctrl-cmd-slash = 'layout tiles accordion'
    alt-ctrl-cmd-backspace = 'close-all-windows-but-current'

    # App shortcuts
    alt-ctrl-cmd-enter = 'exec-and-forget open -n -a Ghostty.app'
    alt-ctrl-cmd-a = 'exec-and-forget open -a ChatGPT.app'
    alt-ctrl-cmd-b = '''exec-and-forget osascript -e '
    tell application "Google Chrome"
        make new window
        activate
    end tell'
    '''
    alt-ctrl-cmd-c = 'exec-and-forget open -a Google\ Chat.app'
    alt-ctrl-cmd-d = 'exec-and-forget open -a Google\ Calendar.app'
    alt-ctrl-cmd-f = '''exec-and-forget osascript -e '
    tell application "Finder"
      set t to (new window target of Finder preferences) as alias
      make new Finder window to t
      activate
    end tell'
    '''
    alt-ctrl-cmd-i = 'exec-and-forget open -a Gmail.app'
    alt-ctrl-cmd-m = 'exec-and-forget open "https://bleech.monday.com/my_inbox"'
    alt-ctrl-cmd-n = 'exec-and-forget open -a Notes.app'
    alt-ctrl-cmd-p = 'exec-and-forget open "https://drive.google.com/drive/folders/1A5sRwrf1xUYMAasHINA11GCLESSSe5RQ"'
    alt-ctrl-cmd-s = 'exec-and-forget open "https://bleech.monday.com/boards/945652202/views/160554991"'
    alt-ctrl-cmd-v = 'exec-and-forget open -a Google\ Meet.app'
    alt-ctrl-cmd-w = 'exec-and-forget open -a iA\ Writer.app'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-ctrl-cmd-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']

    alt-ctrl-cmd-shift-h = ['join-with left', 'mode main']
    alt-ctrl-cmd-shift-j = ['join-with down', 'mode main']
    alt-ctrl-cmd-shift-k = ['join-with up', 'mode main']
    alt-ctrl-cmd-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
  if.app-name-regex-substring = '(1Password|Finder|Messages|Music)'
  run = 'layout floating'

[[on-window-detected]]
  if.app-name-regex-substring = '(Gmail|Google Chat)'
  run = 'move-node-to-workspace 2'

[[on-window-detected]]
  if.app-name-regex-substring = '(Calendar|Notes)'
  run = 'move-node-to-workspace 3'

[[on-window-detected]]
  if.app-name-regex-substring = '(Google Meet|Microsoft Teams|zoom.us)'
  run = 'move-node-to-workspace 4'

